name: Deploy - Serverless

on:
  push:
    branches:
      - development
      - staging
      - production
      - demo
    paths:
      - "serverless/**"
      - "maizzle/**"
      - ".github/workflows/serverless.yml"

jobs:
  build:
    name: Build Maizzle.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/fermium"

      - name: Install yarn dependencies
        run: yarn install --immutable --immutable-cache --check-cache
        working-directory: ./maizzle

      - name: Build maizzle for serverless
        run: yarn build
        working-directory: ./maizzle

      - name: Move maizzle templates to serverless
        run: ./bin/move-maizzle-template.sh -s serverless

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./serverless

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env variable
        run: echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get ENV from AWS SecretManager
        uses: say8425/aws-secrets-manager-actions@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SECRET_NAME: "${{ env.GIT_BRANCH }}/hitpiece/serverless"
          OUTPUT_PATH: "./serverless/.env"

      - name: Set up env.json file
        run: |
          touch env.json
          echo "{" >> env.json
          while IFS='=' read -r var1 var2 || [ -n "$var1" ]; do
            echo "\"${var1}\": \"${var2}\"," >> env.json
          done < <(cat .env)
          echo "}" >> env.json

          sed -zr 's/,([^,]*$)/\1/' env.json >> tmp.json
          mv tmp.json env.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/fermium"

      - name: Install NPM dependencies
        run: npm ci

      - name: Deploy Lambda functions - development
        if: github.ref == 'refs/heads/development'
        run: yarn deploy:dev

      - name: Deploy Lambda functions - staging
        if: github.ref == 'refs/heads/staging'
        run: yarn deploy:stage

      - name: Deploy Lambda functions - demo
        if: github.ref == 'refs/heads/demo'
        run: yarn deploy:demo

      - name: Deploy Lambda functions - production
        if: github.ref == 'refs/heads/production'
        run: yarn deploy:prod
